
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dfc-dev-readonly-role
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["deployments", "replicasets", "pods", "pods/status", "pods/logs", "services", "ingresses", "configmaps", "daemonsets","namespaces"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dfc-dev-readonly-binding
subjects:
- kind: Group
  name: __AksDevGroupObjectId__ # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: dfc-dev-readonly-role
  apiGroup: rbac.authorization.k8s.io