resources:
  repositories:
  - repository: self
  - repository: dfc-devops
    type: github
    name: SkillsFundingAgency/dfc-devops
    endpoint: 'GitHub (ESFA)'
    ref: refs/tags/v1.2.1

pr:
  branches:
    include:
    - master

stages:

- stage: Build
  jobs:
  - job: TestAndPublish
    pool:
      name: 'NCS - CI and CD'
    steps:
    # ARM template
    - template: AzureDevOpsTemplates/Build/dfc-arm-build.yml@dfc-devops
      parameters:
        ArmTemplateRoot: '$(System.DefaultWorkingDirectory)\Resources'
        steps:
    - task: CopyFiles@2
      displayName: 'Copy PSScripts Files to: $(Build.ArtifactStagingDirectory)'
      inputs:
        Contents: 'PSScripts/**/*.ps1'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishPipelineArtifact@0
      displayName: Publish Pipeline Artifact
      inputs:
        targetPath: $(Build.ArtifactStagingDirectory)
        artifactName: Dfc.Shared
    # Also publish build artifact for backwards compatibility
    - task: PublishBuildArtifacts@1
      displayName: Publish Build Artifact
      inputs:
        pathtoPublish: $(Build.ArtifactStagingDirectory)
        artifactName: drop

- stage: DeployToDev
  variables:
  - group: dfc-shared-all
  - group: dfc-shared-infrastructure-all
  - template: VariableTemplates\ReleaseVariables.yml
  - group: 'KeyVault - dfc-dev-shared-kv'
  - group: dfc-shared-dev
  - group: dfc-shared-infrastructure-dev
  - group: dfc-cds-dev
  - template: VariableTemplates\DevVariables.yml
  jobs:
  - template: JobTemplates\Deploy.yml
    parameters:
      AzureSubscription: 'SFA-CDH-Dev/Test (962cae10-2950-412a-93e3-d8ae92b17896)'
      AksAdClientApplicationName: $(AksAdClientApplicationName)
      AksAdServerApplicationName: $(AksAdServerApplicationName)
      AksServicePrincipalName: $(AksServicePrincipalName)
      DfcDevOpsScriptRoot: '$(System.DefaultWorkingDirectory)'
      envAbbreviation: ${{ variables.envAbbreviation }}
      Environment: 'DEV_SHARED'
      EnvironmentTag: ${{ variables.EnvironmentTag }}
      resourceGroup: ${{ variables.resourceGroup }}
      ParentBusinessTag: ${{ variables.ParentBusinessTag }}
      ServiceOfferingTag: ${{ variables.ServiceOfferingTag }}
      SharedKeyVaultName: $(sharedKeyVaultName)