variables:
- name: SolutionBaseName
  value: Dfc.Shared

resources:
  repositories:
  - repository: self
  - repository: dfc-devops
    type: github
    name: SkillsFundingAgency/dfc-devops
    endpoint: 'GitHub (ESFA)'
    ref: refs/tags/v1.10.2

pr:
  branches:
    include:
    - master

pool:
  name: 'NCS - CI and CD'

stages:

- stage: Build
  jobs:
  - job: TestAndPublish
    variables:
      - group: 'KeyVault - dfc-dev-shared-kv'
      - group: dfc-shared-infrastructure-dev
    steps:
    # ARM template
    - template: AzureDevOpsTemplates/Build/StepTemplates/dfc-arm-build.yml@dfc-devops
      parameters:
        ArmTemplateRoot: '$(System.DefaultWorkingDirectory)\Resources'
        SolutionBaseName: $(SolutionBaseName)
        TokenizeTestParameters: true
    - task: CopyFiles@2
      displayName: 'Copy PSScripts Files to: $(Build.ArtifactStagingDirectory)'
      inputs:
        Contents: 'PSScripts/**/*.ps1'
        TargetFolder: '$(Build.ArtifactStagingDirectory)/Resources/PSScripts'
        flattenFolders: true
    - task: PublishPipelineArtifact@0
      displayName: Publish Pipeline Artifact
      inputs:
        targetPath: $(Build.ArtifactStagingDirectory)/Resources/PSScripts
        artifactName: Dfc.Shared.Resources.PSScripts
    # Also publish build artifact for backwards compatibility with classic Release Definition
    - task: PublishBuildArtifacts@1
      displayName: Publish Build Artifact
      inputs:
        pathtoPublish: $(Build.ArtifactStagingDirectory)
        artifactName: drop

- stage: DeployTo_DEV
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  variables:
  - group: dfc-shared-all
  - group: dfc-shared-infrastructure-all
  - template: VariableTemplates\SharedEnvironmentVariables.yml
  - group: 'KeyVault - dfc-dev-shared-kv'
  - group: dfc-shared-dev
  - group: dfc-shared-infrastructure-dev
  - group: dfc-cds-dev
  - template: VariableTemplates\DevEnvironmentVariables.yml
  jobs:
  - template: JobTemplates\Deploy.yml
    parameters:
      AzureSubscription: 'SFA-CDH-Dev/Test (962cae10-2950-412a-93e3-d8ae92b17896)'
      AksAdClientApplicationName: $(AksAdClientApplicationName)
      AksAdServerApplicationName: $(AksAdServerApplicationName)
      AksNodeResourceGroupName: $(AksNodeResourceGroupName)
      AksServicePrincipalName: $(AksServicePrincipalName)
      CertificateIssuerAccountId: $(CertificateIssuerAccountId)
      CertificateIssuerAdministratorPhoneNumber: $(CertificateIssuerAdministratorPhoneNumber)
      CertificateIssuerPassword: $(CertificateIssuerPassword)
      envAbbreviation: ${{ variables.envAbbreviation }}
      Environment: 'DEV_SHARED'
      EnvironmentTag: ${{ variables.EnvironmentTag }}
      ResourceGroup: ${{ variables.resourceGroup }}
      ParentBusinessTag: ${{ variables.ParentBusinessTag }}
      ServiceOfferingTag: ${{ variables.ServiceOfferingTag }}
      SharedKeyVaultName: $(sharedKeyVaultName)
      SharedPrefix: ${{ variables.sharedPrefix }}
      StorageAccountName: $(sharedDfcStorageAccountName)

- stage: DeployTo_SIT
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  variables:
  - group: dfc-shared-all
  - group: dfc-shared-infrastructure-all
  - template: VariableTemplates\SharedEnvironmentVariables.yml
  - group: 'KeyVault - dfc-sit-shared-kv'
  - group: dfc-shared-sit
  - group: dfc-shared-infrastructure-sit
  - group: dfc-cds-sit
  - template: VariableTemplates\SitEnvironmentVariables.yml
  jobs:
  - template: JobTemplates\Deploy.yml
    parameters:
      AzureSubscription: 'SFA-CDH-Dev/Test (962cae10-2950-412a-93e3-d8ae92b17896)'
      AksAdClientApplicationName: $(AksAdClientApplicationName)
      AksAdServerApplicationName: $(AksAdServerApplicationName)
      AksNodeResourceGroupName: $(AksNodeResourceGroupName)
      AksServicePrincipalName: $(AksServicePrincipalName)
      CertificateIssuerAccountId: $(CertificateIssuerAccountId)
      CertificateIssuerAdministratorPhoneNumber: $(CertificateIssuerAdministratorPhoneNumber)
      CertificateIssuerPassword: $(CertificateIssuerPassword)
      envAbbreviation: ${{ variables.envAbbreviation }}
      Environment: 'SIT_SHARED'
      EnvironmentTag: ${{ variables.EnvironmentTag }}
      ResourceGroup: ${{ variables.resourceGroup }}
      ParentBusinessTag: ${{ variables.ParentBusinessTag }}
      ServiceOfferingTag: ${{ variables.ServiceOfferingTag }}
      SharedKeyVaultName: $(sharedKeyVaultName)
      SharedPrefix: ${{ variables.sharedPrefix }}
      StorageAccountName: $(sharedDfcStorageAccountName)

- stage: DeployTo_LAB
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  variables:
  - group: dfc-shared-all
  - group: dfc-shared-infrastructure-all
  - template: VariableTemplates\SharedEnvironmentVariables.yml
  - group: 'KeyVault - dfc-lab-shared-kv'
  - group: dfc-shared-lab
  - group: dfc-shared-infrastructure-lab
  - group: dfc-cds-dev # this mimics the configuration in the classic release definition
  - template: VariableTemplates\LabEnvironmentVariables.yml
  jobs:
  - template: JobTemplates\Deploy.yml
    parameters:
      AzureSubscription: 'SFA-CDH-Dev/Test (962cae10-2950-412a-93e3-d8ae92b17896)'
      AksAdClientApplicationName: $(AksAdClientApplicationName)
      AksAdServerApplicationName: $(AksAdServerApplicationName)
      AksNodeResourceGroupName: $(AksNodeResourceGroupName)
      AksServicePrincipalName: $(AksServicePrincipalName)
      CertificateIssuerAccountId: $(CertificateIssuerAccountId)
      CertificateIssuerAdministratorPhoneNumber: $(CertificateIssuerAdministratorPhoneNumber)
      CertificateIssuerPassword: $(CertificateIssuerPassword)
      envAbbreviation: ${{ variables.envAbbreviation }}
      Environment: 'LAB_SHARED'
      EnvironmentTag: ${{ variables.EnvironmentTag }}
      ResourceGroup: ${{ variables.resourceGroup }}
      ParentBusinessTag: ${{ variables.ParentBusinessTag }}
      ServiceOfferingTag: ${{ variables.ServiceOfferingTag }}
      SharedKeyVaultName: $(sharedKeyVaultName)
      SharedPrefix: ${{ variables.sharedPrefix }}
      StorageAccountName: $(sharedDfcStorageAccountName)