parameters:
  AzureSubscription: ''
  AksAdClientApplicationName: ''
  AksAdServerApplicationName: ''
  AksServicePrincipalName: ''
  ApimApisToRemove: '"Echo API"' #Comma seperated list of strings wrapped in double quotes
  CertificateIssuerAccountId: ''
  CertificateIssuerAdministratorPhoneNumber: ''
  CertificateIssuerPassword: ''
  DfcDevOpsScriptRoot: ''
  envAbbreviation: ''
  Environment: ''
  EnvironmentTag: ''
  ResourceGroup: ''
  ParentBusinessTag: ''
  ServiceOfferingTag: ''
  SharedKeyVaultName: ''
  SharedPrefix: ''
  
jobs:
- deployment: DeployTo_${{ parameters.Environment }}
  pool:
    name: 'NCS - CI and CD'
  variables:
    SetTagsScriptUrl: https://raw.githubusercontent.com/SkillsFundingAgency/dfc-devops/master/PSScripts/Set-EsfaResourceGroupTags.ps1
    SetTagsScriptFilePath: $(System.DefaultWorkingDirectory)\Set-EsfaResourceGroupTags.ps1
    New-ApplicationRegistrationScriptUrl: https://raw.githubusercontent.com/SkillsFundingAgency/dfc-devops/master/PSScripts/New-ApplicationRegistration.ps1
    New-ApplicationRegistrationScriptFilePath: $(System.DefaultWorkingDirectory)\New-ApplicationRegistration.ps1
    Add-AzureAdApiPermissionsToAppScriptUrl: https://raw.githubusercontent.com/SkillsFundingAgency/dfc-devops/master/PSScripts/Add-AzureAdApiPermissionsToApp.ps1
    Add-AzureAdApiPermissionsToAppScriptFilePath: $(System.DefaultWorkingDirectory)\Add-AzureAdApiPermissionsToApp.ps1
  environment: ${{ parameters.Environment }}
  strategy:
    runOnce:
      deploy:
        steps:
        - task: AzurePowerShell@3
          displayName: 'Azure PowerShell script: Set-ArmParameters'
          inputs:
            azureSubscription: ${{ parameters.AzureSubscription }}
            ScriptPath:  '$(Pipeline.Workspace)/Dfc.Shared.Resources.PSScripts/Set-ArmParameters.ps1'
            ScriptArguments: '-Environment "${{ parameters.envAbbreviation }}" -Verbose'
            azurePowerShellVersion: LatestVersion
        - task: PowerShell@2
          name: DownloadNewApplicationRegistrationScript
          displayName: 'Download New-ApplicationRegistration script'
          inputs:
            targetType: 'inline'
            script: Invoke-WebRequest -Uri $(New-ApplicationRegistrationScriptUrl) -OutFile $(New-ApplicationRegistrationScriptFilePath)
        - task: PowerShell@2
          name: DownloadAddAzureAdApiPermissionsToAppSScript
          displayName: 'Download Add-AzureAdApiPermissionsToAppS script'
          inputs:
            targetType: 'inline'
            script: Invoke-WebRequest -Uri $(Add-AzureAdApiPermissionsToAppScriptUrl) -OutFile $(Add-AzureAdApiPermissionsToAppScriptFilePath)
        - task: AzurePowerShell@3
          displayName: 'Azure PowerShell script: New-AksServicePrincipals.ps1'
          inputs:
            azureSubscription: ${{ parameters.AzureSubscription }}
            ScriptPath: '$(Pipeline.Workspace)/Dfc.Shared.Resources.PSScripts/New-AksServicePrincipals.ps1'
            ScriptArguments: '-AksServicePrincipalName ${{ parameters.AksServicePrincipalName }} -AksAdClientApplicationName ${{ parameters.AksAdClientApplicationName }} -AksAdServerApplicationName ${{ parameters.AksAdServerApplicationName }} -DfcDevOpsScriptRoot ${{ parameters.DfcDevOpsScriptRoot }} -SharedKeyVaultName ${{ parameters.SharedKeyVaultName }}'
            azurePowerShellVersion: LatestVersion
        - template: AzureDevOpsTemplates/Deploy/StepTemplates/dfc-arm-deploy.yml@dfc-devops
          parameters:
            ArmTemplateRoot: '$(Pipeline.Workspace)/Dfc.Shared.Resources.ArmTemplates'
            AzureSubscription: ${{ parameters.AzureSubscription }}
            EnvironmentTag: ${{ parameters.EnvironmentTag }}
            ParentBusinessTag: ${{ parameters.ParentBusinessTag }}
            ResourceGroup: ${{ parameters.ResourceGroup }}
            ServiceOfferingTag: ${{ parameters.ServiceOfferingTag }}
        - task: AzurePowerShell@4
          displayName: 'Remove Default APIs from APIM'
          inputs:
            azureSubscription: ${{ parameters.AzureSubscription }}
            ##TO DO: remove this script from dfc-devops when merging this change back to master
            ScriptPath: '$(Pipeline.Workspace)/Dfc.Shared.Resources.PSScripts/Remove-ApisFromApiManagement.ps1'
            ScriptArguments: '-ApisToRemove @( ${{ parameters.ApimApisToRemove }} ) -ApimResourceGroup "${{ parameters.ResourceGroup }}" -ApimServiceName "${{ parameters.SharedPrefix }}-apim"'
            azurePowerShellVersion: LatestVersion
        - task: AzurePowerShell@4
          condition: and(succeededOrFailed(), in('${{ parameters.Environment}}', 'OAT_SHARED', 'PP_SHARED', 'PRD_SHARED'))
          displayName: 'Azure PowerShell script: Set-KeyVaultCertificateIssuer'
          inputs:
            azureSubscription: '${{ parameters.AzureSubscription }}'
            ScriptPath: '$(Pipeline.Workspace)/Dfc.Shared.Resources.PSScripts/Set-KeyVaultCertificateIssuer.ps1'
            ScriptArguments: '-AdministratorPhoneNumber "${{ parameters.CertificateIssuerAdministratorPhoneNumber }}" -CertificateIssuerPassword "${{ parameters.CertificateIssuerPassword }}" -KeyVaultName "${{ parameters.SharedKeyVaultName }}" -CertificateIssuerAccountId "${{ parameters.CertificateIssuerAccountId }}"'
            azurePowerShellVersion: LatestVersion




