parameters:
  AzureSubscription: ''
  AksAdClientApplicationName: ''
  AksAdServerApplicationName: ''
  AksServicePrincipalName: ''
  DfcDevOpsScriptRoot: ''
  envAbbreviation: ''
  Environment: ''
  EnvironmentTag: ''
  resourceGroup: ''
  ParentBusinessTag: ''
  ServiceOfferingTag: ''
  SharedKeyVaultName: ''
  
jobs:
- deployment: DeployToDev
  pool:
    name: 'NCS - CI and CD'
  variables:
    SetTagsScriptUrl: https://raw.githubusercontent.com/SkillsFundingAgency/dfc-devops/master/PSScripts/Set-EsfaResourceGroupTags.ps1
    SetTagsScriptFilePath: $(System.DefaultWorkingDirectory)\Set-EsfaResourceGroupTags.ps1
    New-ApplicationRegistrationScriptUrl: https://raw.githubusercontent.com/SkillsFundingAgency/dfc-devops/master/PSScripts/New-ApplicationRegistration.ps1
    New-ApplicationRegistrationScriptFilePath: $(System.DefaultWorkingDirectory)\New-ApplicationRegistration.ps1
    Add-AzureAdApiPermissionsToAppScriptUrl: https://raw.githubusercontent.com/SkillsFundingAgency/dfc-devops/master/PSScripts/Add-AzureAdApiPermissionsToApp.ps1
    Add-AzureAdApiPermissionsToAppScriptFilePath: $(System.DefaultWorkingDirectory)\Add-AzureAdApiPermissionsToApp.ps1
  environment: ${{ parameters.Environment }}
  strategy:
    runOnce:
      deploy:
        steps:
        - task: AzurePowerShell@3
          displayName: 'Azure PowerShell script: Set-ArmParameters'
          inputs:
            azureSubscription: ${{ parameters.AzureSubscription }}
            ScriptPath:  '$(Pipeline.Workspace)/Dfc.Shared/PSScripts/Set-ArmParameters.ps1'
            ScriptArguments: '-Environment "${{ parameters.envAbbreviation }}" -Verbose'
            azurePowerShellVersion: LatestVersion
        - task: TotalALM.totalalm-tokenization.tokenization-build-task.Tokenization@2
          displayName: 'Tokenization: Transform file parameters.json'
          inputs:
            SourcePath: '$(Pipeline.Workspace)/Dfc.Shared/ArmTemplates'
            TargetFileNames: parameters.json
        - task: PowerShell@2
          name: DownloadSetEsfaResourceGroupTagsScript
          displayName: 'Download Set-EsfaResourceGroupTags script'
          inputs:
            targetType: 'inline'
            script: Invoke-WebRequest -Uri $(SetTagsScriptUrl) -OutFile $(SetTagsScriptFilePath)
        - task: AzurePowerShell@3
          displayName: 'Resource group tagging'
          inputs:
            azureSubscription: ${{ parameters.AzureSubscription }}
            scriptType: filePath
            ScriptPath: $(SetTagsScriptFilePath)
            ScriptArguments: '-ResourceGroupName ${{ parameters.resourceGroup }} -Environment "${{ parameters.EnvironmentTag }}" -ParentBusiness "${{ parameters.ParentBusinessTag }}" -ServiceOffering "${{ parameters.ServiceOfferingTag }}"'
            azurePowerShellVersion: LatestVersion
        - task: PowerShell@2
          name: DownloadNewApplicationRegistrationScript
          displayName: 'Download New-ApplicationRegistration script'
          inputs:
            targetType: 'inline'
            script: Invoke-WebRequest -Uri $(New-ApplicationRegistrationScriptUrl) -OutFile $(New-ApplicationRegistrationScriptFilePath)
        - task: PowerShell@2
          name: DownloadAddAzureAdApiPermissionsToAppSScript
          displayName: 'Download Add-AzureAdApiPermissionsToAppS script'
          inputs:
            targetType: 'inline'
            script: Invoke-WebRequest -Uri $(Add-AzureAdApiPermissionsToAppScriptUrl) -OutFile $(Add-AzureAdApiPermissionsToAppScriptFilePath)
        - task: AzurePowerShell@3
          displayName: 'Azure PowerShell script: New-AksServicePrincipals.ps1'
          inputs:
            azureSubscription: ${{ parameters.AzureSubscription }}
            ScriptPath: '$(Pipeline.Workspace)/Dfc.Shared/PSScripts/New-AksServicePrincipals.ps1'
            ScriptArguments: '-AksServicePrincipalName ${{ parameters.AksServicePrincipalName }} -AksAdClientApplicationName ${{ parameters.AksAdClientApplicationName }} -AksAdServerApplicationName ${{ parameters.AksAdServerApplicationName }} -DfcDevOpsScriptRoot ${{ parameters.DfcDevOpsScriptRoot }} -SharedKeyVaultName ${{ parameters.SharedKeyVaultName }}'
            azurePowerShellVersion: LatestVersion
        - task: AzureResourceGroupDeployment@2
          displayName: 'Azure Deployment: Shared infrastructure'
          inputs:
            azureSubscription: ${{ parameters.AzureSubscription }}
            resourceGroupName: '${{ parameters.resourceGroup }}'
            location: 'West Europe'
            csmFile: '$(Pipeline.Workspace)/Dfc.Shared/ArmTemplates/template.json'
            csmParametersFile: '$(Pipeline.Workspace)/Dfc.Shared/ArmTemplates/parameters.json'
            deploymentOutputs: ARMOutputs